# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: jmtirado.net
email:
description: JM Tirado personal website.
twitter_username: jmtirado
github_username: juanmanuel-tirado
minimal_mistakes_skin: contrast
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: ES # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

analytics:
  provider: 'google-gtag'
  google:
    tracking_id: 'UA-162071617-1'
    anonymize_ip: false # default

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: 'Juan M. Tirado'
  avatar: '/assets/images/bio-photo.jpg'
  bio: 'Computer scientist interested in data and large scale distributed systems. I enjoy music, mountaneering, and tapas in no particular order.'
  links:
    - label: 'Website'
      icon: 'fas fa-fw fa-link'
      url: 'https://jmtirado.net'
    - label: 'Twitter'
      icon: 'fab fa-fw fa-twitter-square'
      url: 'https://twitter.com/jmtirado'
    - label: 'GitHub'
      icon: 'fab fa-fw fa-github'
      url: 'https://github.com/juanmanuel-tirado'
    - label: 'LinkedIn'
      icon: 'fab fa-fw fa-linkedin'
      url: 'https://www.linkedin.com/in/juan-tirado'
    - label: 'Medium'
      icon: 'fab fa-fw fa-medium'
      url: 'https://juanmanuel-tirado.medium.com'

footer:
  links:
    - label: 'Twitter'
      icon: 'fab fa-fw fa-twitter-square'
      url: 'https://twitter.com/jmtirado'
    - label: 'GitHub'
      icon: 'fab fa-fw fa-github'
      url: 'https://github.com/juanmanuel-tirado'
    - label: 'LinkedIn'
      icon: 'fab fa-fw fa-linkedin'
      url: 'https://www.linkedin.com/in/juan-tirado'
    - label: 'Medium'
      icon: 'fab fa-fw fa-medium'
      url: 'https://juanmanuel-tirado.medium.com'

defaults:
  # _pages
  - scope:
      path: '_pages'
      type: pages
    values:
      layout: splash
      author_profile: true
  # _posts
  - scope:
      path: '_posts'
      type: posts
    values:
      layout: single
      classes: wide
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
